### ISSUE TITLE
Prefer os.path.join(folder1, folder2) instead of str(folder1, folder2)

### ISSUE THREAD

**Issue by mynamewastaken** [tinfoil-hacks/steam-mv#1]
https://github.com/tinfoil-hacks/steam-mv/blob/4943612be7db61bea0c3a09603420097a4a32357/steam-mv#L74

https://docs.python.org/3.3/library/os.path.html#os.path.join

**Comment by oaksisfolks** [comment]
I'm using Path from pathlib. https://docs.python.org/3/library/pathlib.html#pathlib.Path

It can definitely be cleaned up, for sure. But I'm not using os.path.join. It's annoying.

**Comment by oaksisfolks** [comment]
I cleaned it up.
